### ISSUE TITLE
Contribution.md is missing.

### ISSUE THREAD

**Issue by muratbeser** [DutchKevv/TradeJS#1]
Contribution.md is missing, I would like to put some work on this project.

**Comment by DutchKevv** [comment]
Hi @muratbeser, thanks for showing interest in TradeJS. I added a Contribution file in the development branch, will be in master soon.

https://github.com/DutchKevv/TradeJS/commit/0611f4482135cf9de43d20ca7f10076ac52a7f42

For now TradeJS is just a big side project, a lot of stuff keeps being refactored every now and then ;) So consider not to make big pull requests and rather small ones. 

Thanks!

**Comment by DutchKevv** [comment]
Fixed in
